queue_rules:
  - name: default
    conditions:
      - check-success=test
      - check-success=Codacy Static Code Analysis

pull_request_rules:
  - name: automatic merge for scala-steward PRs
    conditions:
      - author=scala-steward
      - check-success=test
      - check-success=Codacy Static Code Analysis
    actions:
      queue:
        name: default
        method: squash
