queue_rules:
  - name: default
    queue_conditions:
      - author=scala-steward
      - check-success=test
      - check-success=Codacy Static Code Analysis
    merge_conditions:
      - check-success=test
      - check-success=Codacy Static Code Analysis
    merge_method: squash

pull_request_rules:
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
