addSbtPlugin("com.github.sbt"            % "sbt-release"    % "1.1.0")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"   % "2.5.0")
addSbtPlugin("com.github.sbt"            % "sbt-ci-release" % "1.5.12")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"  % "2.0.8")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"   % "0.4.2")
