addSbtPlugin("com.github.sbt" % "sbt-release"    % "1.1.0")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"   % "2.5.2")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.5.12")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"  % "2.0.8")
addSbtPlugin("org.typelevel"  % "sbt-tpolecat"   % "0.5.0")
