addSbtPlugin("com.github.sbt"            % "sbt-release"    % "1.1.0")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"   % "2.4.3")
addSbtPlugin("com.github.sbt"              % "sbt-ci-release" % "1.5.9")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"  % "1.9.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"   % "0.1.20")
